# Generated by Django 5.2.6 on 2025-09-08 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_created_at_blogpost_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='document',
            field=models.FileField(null=True, upload_to='blog_post_documents/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(null=True, upload_to='blog_post_picture/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='website',
            field=models.URLField(null=True, verbose_name='ვებ მისამართი'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='შექმნის თარიღი'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='განახლების თარიღი'),
            preserve_default=False,
        ),
    ]
